### ISSUE TITLE
Mamba_simple.py替换的必要性问题

### ISSUE THREAD

**Issue by ParkMinyoung0304** [PSRben/FusionMamba#3]
作者您好！
关于mamba_simple.py文件的替换，我想请问我之前安装的是mamba-ssm=1.1.1，会有一个mamba_simple.py文件，里面的内容和您的在开头有些相似，但代码行数只有400行左右，远少于您的代码数，请问这样的替换会不会对项目的运行产生影响

<img width="1694" alt="mamba_simple py_contrast" src="https://github.com/user-attachments/assets/f065ecb6-c68d-4186-8cd8-eabb65341c3d">

**Comment by PSRben** [comment]
会，而且单纯用我的mamba_simple.py替换官方的mamba_simple.py大概率跑不通。因为我的mamba_simple.py基于Vision Mamba的代码。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月15日 下午4:38 |
| 收件人 | PSRben/FusionMamba ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [PSRben/FusionMamba] Mamba_simple.py替换的必要性问题 (Issue #3) |

作者您好！
关于mamba_simple.py文件的替换，我想请问我之前安装的是mamba-ssm=1.1.1，会有一个mamba_simple.py文件，里面的内容和您的在开头有些相似，但代码行数只有400行左右，远少于您的代码数，请问这样的替换会不会对项目的运行产生影响

mamba_simple.py_contrast.png (view on web)

**Comment by ParkMinyoung0304** [comment]
感谢您的回答！
请问如果直接用官方ssm的Mamba_Simple.py替换，是否会影响到您文章中提及的Fusion功能

**Comment by PSRben** [comment]
会，而且大概率会报错

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月15日 下午7:44 |
| 收件人 | ***@***.***> |
| 抄送人 | PSRben ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [PSRben/FusionMamba] Mamba_simple.py替换的必要性问题 (Issue #3) |

感谢您的回答！
请问如果直接用官方ssm的Mamba_Simple.py替换，是否会影响到您文章中提及的Fusion功能

**Comment by ParkMinyoung0304** [comment]
请问是配完Vision Mamba的环境后，再用官方的Mamba_Simple.py替换您项目中的代码，来跑该项目的train.py吗？

**Comment by PSRben** [comment]
配完Vision Mamba的环境后，用我的mamba_simple.py替换vision mamba里的mamba_simple.py

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年10月15日 下午7:52 |
| 收件人 | PSRben/FusionMamba ***@***.***> |
| 抄送人 | PSRben ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [PSRben/FusionMamba] Mamba_simple.py替换的必要性问题 (Issue #3) |

请问是配完Vision Mamba的环境后，再用官方的Mamba_Simple.py替换您项目中的代码，来跑该项目的train.py吗？

**Comment by ParkMinyoung0304** [comment]
非常感谢！之前误会了readme里面的意思
