### ISSUE TITLE
关于训练配置和时长问题

### ISSUE THREAD

**Issue by chingguo** [PSRben/FusionMamba#7]
非常感谢作者的研究，他对我很有参考价值！想问一下作者训练时用了几块3090，大概需要训练多久？

**Comment by PSRben** [comment]
用了1块，500轮迭代8个小时

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月23日 下午4:35 |
| 收件人 | PSRben/FusionMamba ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [PSRben/FusionMamba] 关于训练配置和时长问题 (Issue #7) |

非常感谢作者的研究，他对我很有参考价值！想问一下作者训练时用了几块3090，大概需要训练多久？

**Comment by chingguo** [comment]
好的 谢谢！
